### ISSUE TITLE
Consider adding CORS support

### ISSUE THREAD

**Issue by matthewkmayer** [gomicro/duty#7]
A welcome feature would be allowing CORS preflight OPTIONS responses. An example use case: running a local web application that points directly at `duty`.

While [avenues](https://github.com/gomicro/avenues) can be used to achieve this, it may be worth the implementation cost in this repo for simpler setup for end users.

**Comment by dan9186** [comment]
<img width="636" alt="Screen Shot 2020-03-14 at 12 07 43 AM" src="https://user-images.githubusercontent.com/777141/76677131-e2e6fa80-6587-11ea-80a1-44b2812b9665.png">
New image pushed with CORS response implemented
