### ISSUE TITLE
Consider adding HTTP verb routing for different responses

### ISSUE THREAD

**Issue by matthewkmayer** [gomicro/duty#8]
Desired behavior: be able to handle a GET to `/v1/foo` to get all the `foo`s. Also be able to POST to `/v1/foo` to create a new `foo`.

Potential config example:

```yaml
- endpoint: "/foo"
  type: "verb"
    responses:
      - verb: GET
        code: 200
        payload: "/responses/foos.json"
      - verb: POST
        code: 201
        payload: "/responses/newfoo.json"
```

**Comment by dan9186** [comment]
<img width="730" alt="Screen Shot 2020-03-14 at 1 04 30 AM" src="https://user-images.githubusercontent.com/777141/76677822-eb433380-658f-11ea-97ef-5bab3099b35f.png">
